name: ngenius_sdk
description: "A Flutter plugin for processing payments with Ngenius."
version: 0.0.2
homepage: "https://ameerrizvi.online"

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  dio: ^5.5.0+1
  json_annotation: ^4.9.0
  flutter_inappwebview: ^5.8.0
  text_form_field_wrapper: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.ngenius_sdk
        pluginClass: NgeniusSdkPlugin
      ios:
        pluginClass: NgeniusSdkPlugin
